[project]
name = "publish-crawler"
authors = ["Publish Crawler Team"]
description = "Decentralized Content Publishing Platform"
telemetry = false
requirements = []
[contracts.publish-crawler]
path = "contracts/publish-crawler.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
